In [2]:
import torch
torch.cuda.is_available()


True

In [4]:
#q1

a=torch.tensor([2.],requires_grad=True)
b=torch.tensor([2.],requires_grad=True)
x=2*a+3*b
y=5*a*a+3*b*b*b
z=2*x+3*y

z.backward()

print(a.grad)
print(b.grad)

tensor([64.])
tensor([114.])


In [7]:
#q2
import torch.nn as nn
b=torch.tensor([1.],requires_grad=True)
x=torch.tensor([5.],requires_grad=True)
w=torch.tensor([1.],requires_grad=True)

u=w*x
v=u+b
relu=torch.nn.ReLU()
a=relu(v)

a.backward()

print(w.grad)




tensor([5.])


In [4]:
#q3

import torch

x=torch.tensor([2.],requires_grad=True)
w=torch.tensor([5.],requires_grad=True)
b=torch.tensor([3.],requires_grad=True)

u=w*x
v=u+b
a=torch.sigmoid(v)
a.backward()
print("da/dw: ", w.grad.item())
analytically = (a*(1-a))*x
print("analytical:",analytically)
      



da/dw:  4.529942543740617e-06
analytical: tensor([4.5299e-06], grad_fn=<MulBackward0>)


In [5]:
#q4
x = torch.tensor(2.0, requires_grad=True)
a = x*x
b = 2*x
c = torch.sin(x)
d = -(a)-(b)-(c)
f = torch.exp(d)
f.backward()
print("df/dx:",x.grad)
diff = f*(-(2*x)-2-torch.cos(x))
print("analytical:",diff)

df/dx: tensor(-0.0008)
analytical: tensor(-0.0008, grad_fn=<MulBackward0>)


In [6]:
#q5
x = torch.tensor(2.0,requires_grad = True)
y = (8*x**4)+(3*x**3)+(7*x**2)+6*x+3
y.backward()
print("dy/dx:", x.grad)
analytical = (32*x**3)+(9*x**2)+14*x+6
print("analytically:",analytical)

dy/dx: tensor(326.)
analytically: tensor(326., grad_fn=<AddBackward0>)
