In [1]:
import torch
torch.cuda.is_available()


True

In [2]:
#q1
import torch
tensor = torch.Tensor([[1,2,3],[4,5,6]])
print("shape of tensor :",tensor.shape)
print("rank of a tensor :",len(tensor.shape))
print("total number of elements :",tensor.numel())
reshape_tensor = torch.reshape(tensor,(3,2))
print(reshape_tensor)
#squeezing
sq_tensor = tensor.reshape([1,6]).squeeze()
print(sq_tensor)
print(tensor.shape,sq_tensor.shape)
#it will print as it is if there is no one
# sec_sq_tensor = sq_tensor.squeeze()
# print(sec_sq_tensor)
#unsqueeze
un_sq_tensor = sq_tensor.unsqueeze(dim = 0)
un_sq_tensor1 = sq_tensor.unsqueeze(dim = 1)
print(un_sq_tensor1)
print(sq_tensor.shape,un_sq_tensor.shape, un_sq_tensor1.shape)
#stack
x = torch.tensor([1,2,3,4])
y = torch.tensor([5,6,7,8])
stack_tensor = torch.stack((x,y),dim = 0)
print(stack_tensor)

print(tensor.view((3,2)))
print(tensor)

shape of tensor : torch.Size([2, 3])
rank of a tensor : 2
total number of elements : 6
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([1., 2., 3., 4., 5., 6.])
torch.Size([2, 3]) torch.Size([6])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])
torch.Size([6]) torch.Size([1, 6]) torch.Size([6, 1])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [3]:
#q2
#based on the index the dimension will be changed
permute_tensor = torch.permute(tensor,(1,0))
print(tensor.shape,permute_tensor.shape)

torch.Size([2, 3]) torch.Size([3, 2])


In [4]:
#q3
indices = torch.tensor([0,1])
index_tensor = torch.index_select(tensor,1,indices)
print(index_tensor)

tensor([[1., 2.],
        [4., 5.]])


In [5]:
#q4
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
numpy_tensor = torch.from_numpy(a)
print(numpy_tensor,a)
numpy_array = numpy_tensor.numpy()
print(numpy_array)

tensor([[1, 2, 3],
        [4, 5, 6]]) [[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [6]:
#q5
random_tensor = torch.randint(1,10,(7,7))
print(random_tensor)


tensor([[3, 2, 4, 9, 2, 7, 9],
        [8, 8, 5, 5, 1, 8, 3],
        [2, 5, 7, 8, 2, 2, 5],
        [7, 3, 1, 1, 5, 4, 8],
        [2, 1, 7, 5, 5, 7, 1],
        [2, 2, 3, 4, 7, 2, 4],
        [3, 9, 6, 1, 1, 3, 7]])


In [7]:
#q6
sec_tensor = torch.randint(1,10,(1,7))
#matmultiplication..
print(torch.matmul(random_tensor,sec_tensor.T))

tensor([[162],
        [166],
        [114],
        [146],
        [100],
        [ 94],
        [118]])


In [8]:
#q7
tensor2 = torch.randint(1,6,(2,3))
print(tensor, tensor.device)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) cpu
tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [9]:
#q8
adjusted_tensor = torch.reshape(sec_tensor,(7,1))
mult_tensor = torch.matmul(random_tensor,adjusted_tensor)
print(mult_tensor)

tensor([[162],
        [166],
        [114],
        [146],
        [100],
        [ 94],
        [118]])


In [10]:
#q9
print(mult_tensor.max())
print(mult_tensor.min())

tensor(166)
tensor(94)


In [11]:
#q10
print(torch.argmax(mult_tensor))
print(torch.argmin(mult_tensor))

tensor(1)
tensor(5)


In [12]:
#q11
t = torch.randn((1,1,1,10))
sec_t = t.squeeze()
print(t,sec_t)
print(t.shape,sec_t.shape)

tensor([[[[ 0.7837, -1.2726, -1.4124, -0.8632, -0.0092, -0.3163,  0.8352,
            0.2417, -0.7754,  0.2349]]]]) tensor([ 0.7837, -1.2726, -1.4124, -0.8632, -0.0092, -0.3163,  0.8352,  0.2417,
        -0.7754,  0.2349])
torch.Size([1, 1, 1, 10]) torch.Size([10])
